### ISSUE TITLE
LVOGL (Velocity v0.5.1.7): Lighting glitch when too many light sources are allocated.

### ISSUE THREAD

**Issue by hockeyPlayer882** [RSC-Games/Velocity#4]
This glitch occurred while messing around in the mining game. It resulted after a series of light sources were created, moved, offscreen, then more light sources were placed. The glitch makes almost everything turn bright white and only shows certain colors and the outline of certain sprites.
![Screenshot 2024-04-17 094819](https://github.com/RSC-Games/Velocity/assets/163692984/2d867188-aa23-4f23-a293-ea1139c0b7d6)

**Comment by RSC-Games** [comment]
I may have an insight into this issue.

I will need to do further testing and the elusiveness of this bug makes test case development difficult but I have my suspicions.
I'm currently of the opinion that while the deallocated light sources are awaiting finalization, too many of them pile up and overflow the 128 light sources allowed by the shader. Since this is the case, and no length validation is performed, LVOGL may be writing outside the bounds of the lighting data array. And that may be corrupting other associated data (since out of bounds access is not good) and resulting in maximum brightness calculation for all fragments.

Now that I think about it, this likely is the issue. And it probably has to do with the ```illuminate``` function in ```lit.frag```. Validating the light source count and uniform upload from the CPU side would help matters (and prevent the counter uniform from exceeding the length of the uniform LightSource array, so we can avoid a bounds test every fragment). So I'll fix that and merge that into mainline in a couple of weeks.

**Comment by RSC-Games** [comment]
In the latest LVOGL release, this may have been patched. The transient nature of the bug makes it hard to know, and the work on LVOGL is not complete, so this issue will remain open.

**Comment by RSC-Games** [comment]
See #8

**Comment by RSC-Games** [comment]
Tested on Velocity v0.6.3.4-dev with LVOGL in the Velocity Tilemap Editor. Bug patched.
